# Copyright (c) 2020-2024, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto. Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#

"""
Robot spawning module for Isaac Sim.

This module provides functionality to spawn robots into the Isaac Sim stage.
It supports both URDF and USD input formats:
- URDF: Imported directly using convert_urdf module (for Isaac Sim)
- USD: Loaded as a reference into the stage

Usage:
    # Spawn from URDF (imports directly into current stage)
    spawn.main("/path/to/robot.urdf", x=0, y=0, z=0.5)

    # Spawn from pre-converted USD
    spawn.spawn_from_usd("/path/to/robot.usd", x=0, y=0, z=0.5)
"""

import os
import math
import omni
import omni.kit.commands
import omni.usd
from pxr import UsdGeom, Gf, Sdf, Usd


def spawn_from_usd(
    usd_path: str,
    x: float = 0.0,
    y: float = 0.0,
    z: float = 0.0,
    roll: float = 0.0,
    pitch: float = 0.0,
    yaw: float = 0.0,
    prim_path: str = None,
):
    """
    Spawn a robot from a USD file into the current stage.

    This function loads a pre-converted USD file as a reference.
    For Isaac Lab, use this with USD files generated by convert_urdf.convert_urdf_to_usd().

    Args:
        usd_path: Path to the USD file
        x, y, z: Position in world coordinates (meters)
        roll, pitch, yaw: Orientation in radians
        prim_path: Optional prim path for the robot. If None, uses the root prim
                   name from the USD file.

    Returns:
        The spawned prim object
    """
    if not os.path.exists(usd_path):
        raise FileNotFoundError(f"USD file not found: {usd_path}")

    stage = omni.usd.get_context().get_stage()

    # Determine prim path
    if prim_path is None:
        # Load USD to get root prim name
        temp_stage = Usd.Stage.Open(usd_path)
        root_prims = [p for p in temp_stage.GetPseudoRoot().GetChildren()]
        if root_prims:
            prim_path = "/" + root_prims[0].GetName()
        else:
            prim_path = "/Robot"
        del temp_stage

    # Check if prim already exists and generate unique name if needed
    base_path = prim_path
    counter = 1
    while stage.GetPrimAtPath(prim_path).IsValid():
        prim_path = f"{base_path}_{counter}"
        counter += 1

    # Add reference to the USD file
    prim = stage.DefinePrim(prim_path)
    prim.GetReferences().AddReference(usd_path)

    # Apply transform
    if prim.IsValid():
        obj_xform = UsdGeom.Xformable(prim)
        obj_xform.ClearXformOpOrder()

        translate_op = obj_xform.AddTranslateOp()
        translate_op.Set((x, y, z))

        rotate_op = obj_xform.AddRotateXYZOp()
        rotate_op.Set((
            roll * 180.0 / math.pi,
            pitch * 180.0 / math.pi,
            yaw * 180.0 / math.pi
        ))

    print(f"[spawn] Spawned robot from USD at {prim_path}")
    return prim


def main(
    urdf_path: str,
    x: float = 0.0,
    y: float = 0.0,
    z: float = 0.0,
    roll: float = 0.0,
    pitch: float = 0.0,
    yaw: float = 0.0,
    fixed: bool = False,
):
    """
    Spawn a robot from a URDF file into the current stage.

    This function imports the URDF directly into the current stage,
    applying custom Isaac Sim attributes (isaac_drive_api, isaac_rigid_body, etc.).

    This is the recommended method for spawning robots during Isaac Sim runtime.

    Args:
        urdf_path: Path to the URDF file
        x, y, z: Position in world coordinates (meters)
        roll, pitch, yaw: Orientation in radians
        fixed: Whether to fix the robot base to the world

    Returns:
        The spawned prim object
    """
    import convert_urdf

    # Import URDF directly to current stage
    stage_path, robot_name = convert_urdf.import_urdf_to_stage(
        urdf_path=urdf_path,
        fixed_base=fixed,
    )

    # Get the spawned prim and apply transform
    stage = omni.usd.get_context().get_stage()
    obj = stage.GetPrimAtPath(stage_path)

    if obj.IsValid():
        obj_xform = UsdGeom.Xformable(obj)
        xform_ops = obj_xform.GetOrderedXformOps()

        obj_xform.ClearXformOpOrder()

        translate_op = obj_xform.AddTranslateOp()
        translate_op.Set((x, y, z))

        rotate_op = obj_xform.AddRotateXYZOp()
        rotate_op.Set((
            roll * 180.0 / math.pi,
            pitch * 180.0 / math.pi,
            yaw * 180.0 / math.pi
        ))

    print(f"[spawn] Spawned robot from URDF at {stage_path}")
    return obj


# Legacy function signature for backward compatibility
def spawn_robot(
    urdf_path: str,
    x: float = 0.0,
    y: float = 0.0,
    z: float = 0.0,
    roll: float = 0.0,
    pitch: float = 0.0,
    yaw: float = 0.0,
    fixed: bool = False,
):
    """
    Legacy function for backward compatibility.
    Use main() or spawn_from_usd() instead.
    """
    return main(urdf_path, x, y, z, roll, pitch, yaw, fixed)
